spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${TDB_DEV_DB_HOST}
    username: ${TBD_DEV_DB_USER}
    password: ${TBD_DEV_DB_PASS}
    hikari:
      maximum-pool-size: 3

eureka:
  client:
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
    hostname: ${EUREKA_URL}
    nonSecurePort: 80
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
