eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@lms-eureka.herokuapp.com}/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
